pool:
   name: Live Cluster
stages:
  - stage: DeployLive
    displayName: Deploylive
    jobs:
    - deployment: deploymentjob
      displayName: Deployment Job
      environment:
       name: Live
       resourceType: VirtualMachine
      strategy:                 
        rolling:
          maxParallel: 1
          deploy: 
            steps:       
            - script: |
               hostname
               date
               docker ps
              displayName: Testing live cluster