stages:
  - stage: CommitLatestDockerChanges
    displayName: DockerChanges
    jobs:
    - deployment: gitcommit
      displayName: Git Commit
      environment:
       name: dev
       resourceType: VirtualMachine
      pool:
       name: Staging
      strategy:                 
        rolling:
          maxParallel: 1
          deploy: 
            steps:       
            - script: |
               hostname
               date
               cd /home/dorset/docker-geoserver
               git status
              displayName: Commit Latest Changes
  - stage: PullLatestChanges
    displayName: Pull Changes
    jobs:
    - deployment: pulllatestchanges
      displayName: Pull Latest Changes
      environment:
       name: Live
       resourceType: VirtualMachine
      pool:
       name: Live Cluster
      strategy:                 
        rolling:
          maxParallel: 1
          deploy: 
            steps:       
            - script: |
               hostname
               date
               mkdir -p /home/dorset/geosolutions/
               cd /home/dorset/geosolutions/
               rm -rf /home/dorset/geosolutions/Docker%20Configuration/
               git clone https://jovg65mehr5gj3h6e4sjezzhgvzeljnxwu2jbc5c4dmhsz5ckvrq:3RDP.GEOSOLUTIONS@dev.azure.com/dccgisvsts/Docker%20Configuration/_git/Docker%20Configuration
               cd Docker%20Configuration/
               git checkout master
               git status
               cat .gitignore
               ls -al
              displayName: Git Pull Latest Changes