jobs:
- deployment: Build
  environment: dev
  pool:
    name: Staging
  strategy:                 
    runOnce:            
      deploy: 
        steps:       
        - script: hostname

- deployment: Deploy
  environment: dev
  pool:
    name: Staging
  strategy:                 
    runOnce:
      deploy: 
        steps:       
        - script: hostname