 stages:
   - stage: DeployLive
     displayName: Deploy to Live
     jobs:
       - deployment: Deploy
         environment: Live
         pool:
          name: Live Cluster
         strategy:                 
          runOnce:
            deploy: 
              steps:       
            - script: |
                hostname
                docker ps
                 
              displayName: Testing live cluster


