jobs:
- deployment:
  environment: dev
  pool:
    name: Azure Pipelines
  strategy:                 
    runOnce:            
      deploy: 
        steps:       
        - script: hostname

- deployment: deployDB
  environment: dev
  strategy:                 
    runOnce:
      deploy: 
        steps:       
        - script: hostname