jobs:
- deployment: geoserverdatadir
  environment: dev
  pool:
    name: Staging
  strategy:                 
    runOnce:
      deploy: 
        steps:       
        - script: |
           hostname
           cd /mnt/data_dir
           git checkout --track dorset/datadir-test
           git add .
           git commit -m "`date` datadir test"
           git push -u dorset datadir-test
          displayName: GeoServer Datadir Save Latest Changes

