pool:
   name: Live Cluster
stages:
  - stage: DeployLive
    displayName: Deploylive
    jobs:
    - deployment: deploymentjob
      displayName: Deployment Job
      environment:
       name: Live
       resourceType: VirtualMachine
      strategy:                 
        runOnce:
          deploy: 
            steps:       
            - script: |
               hostname
               date
               whoami
               find /home/dorset/ -name docker-compose.yml
               cat /home/dorset/docker-geoserver/docker-compose.yml
               ls -al /home/dorset/docker-geoserver/
               docker ps
              displayName: Testing live cluster