jobs:
- deployment: Deploy
  environment: Live
  pool:
    name: Live Cluster
  strategy:                 
    runOnce:
      deploy: 
        steps:       
        - script: |
           hostname
           docker ps
          displayName: Testing live cluster

