jobs:
- deployment: Deploy
  environment: dev
  pool:
    name: Staging
  strategy:                 
    runOnce:
      deploy: 
        steps:       
        - script: |
           cd /home/dorset/geosolutions/docker-nginx-hello-world
           docker run -p 3333:9090 -d dockerbogo/docker-nginx-hello-world
           docker ps
          displayName: Testing again

