pool:
   name: Live Cluster
stages:
  - stage: DeployLive
    displayName: Deploylive
    jobs:
    - deployment: Deploy
      environment:
       name: Live
       resourceName: vchgisliveapp3
       resourceType: VirtualMachine
       tags: Console
      strategy:                 
        runOnce:
          deploy: 
            steps:       
            - script: |
               hostname
               docker ps
              displayName: Testing live cluster