jobs:
- deployment: Deploy
  environment: dev
  pool:
    name: Staging
  strategy:                 
    runOnce:
      deploy: 
        steps:       
        - script: |
           hostname
           date
           docker ps
          displayName: Testing

